/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.pierluigi.finted_android.models

import it.unical.demacs.pierluigi.finted_android.models.UserDto

/**
 * 
 * @param id 
 * @param title 
 * @param startingPrice 
 * @param seller 
 * @param purchaseDate 
 * @param publishDate 
 * @param postImage 
 */
data class PostPublishDto (

    val id: kotlin.Long? = null,
    val title: kotlin.String,
    val startingPrice: kotlin.Long,
    val seller: UserDto? = null,
    val purchaseDate: java.time.LocalDateTime? = null,
    val publishDate: java.time.LocalDateTime? = null,
    val postImage: kotlin.String? = null
) {
}