/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.pierluigi.finted_android.models

import it.unical.demacs.pierluigi.finted_android.models.UserBasicInfoDto
import it.unical.demacs.pierluigi.finted_android.models.UserDto

/**
 * 
 * @param id 
 * @param author 
 * @param user 
 * @param publishDate 
 * @param content 
 */
data class ReviewPublishDto (

    val id: kotlin.Long? = null,
    val author: UserBasicInfoDto? = null,
    val user: UserDto? = null,
    val publishDate: java.time.LocalDateTime? = null,
    val content: kotlin.String
) {
}