/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.pierluigi.finted_android.models

import it.unical.demacs.pierluigi.finted_android.models.AddressDto
import it.unical.demacs.pierluigi.finted_android.models.CredentialsRegistrationDto

/**
 * 
 * @param id 
 * @param firstName 
 * @param lastName 
 * @param registrationDate 
 * @param address 
 * @param credentials 
 */
data class UserRegistrationDto (

    val id: kotlin.Long? = null,
    val firstName: kotlin.String,
    val lastName: kotlin.String,
    val registrationDate: java.time.LocalDateTime? = null,
    val address: AddressDto? = null,
    val credentials: CredentialsRegistrationDto? = null
) {
}