/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ImageDto } from './imageDto';
import { UserDto } from './userDto';

export interface PostPublishDto {
    id?: number;
    title: string;
    startingPrice: number;
    seller?: UserDto;
    purchaseDate?: Date;
    publishDate?: Date;
    postImages?: ImageDto;
}
