/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserBasicInfoDto } from './userBasicInfoDto';
import { UserDto } from './userDto';

export interface ReviewPublishDto { 
    id?: number;
    author?: UserBasicInfoDto;
    user?: UserDto;
    publishDate?: Date;
    content: string;
}