/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.pierluigi.finted_android.apis

import it.unical.demacs.pierluigi.finted_android.models.FavouriteDto
import it.unical.demacs.pierluigi.finted_android.models.FavouritePublishDto
import it.unical.demacs.pierluigi.finted_android.models.ServiceError

import it.unical.demacs.pierluigi.finted_android.infrastructure.*

class FavouriteControllerApi(basePath: kotlin.String = "http://localhost:8080") : ApiClient(basePath) {

    /**
     * 
     * 
     * @param id  
     * @return void
     */
    fun delete4(id: kotlin.Long): Unit {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/likes/{id}".replace("{" + "id" + "}", "$id")
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param userId  
     * @return kotlin.Array<FavouriteDto>
     */
    @Suppress("UNCHECKED_CAST")
    fun getFollow(userId: kotlin.Long): kotlin.Array<FavouriteDto> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/likes/follow/{user-id}".replace("{" + "user-id" + "}", "$userId")
        )
        val response = request<kotlin.Array<FavouriteDto>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<FavouriteDto>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param userId  
     * @return kotlin.Array<FavouriteDto>
     */
    @Suppress("UNCHECKED_CAST")
    fun getFollowers(userId: kotlin.Long): kotlin.Array<FavouriteDto> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/likes/followers/{user-id}".replace("{" + "user-id" + "}", "$userId")
        )
        val response = request<kotlin.Array<FavouriteDto>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<FavouriteDto>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param body  
     * @return FavouriteDto
     */
    @Suppress("UNCHECKED_CAST")
    fun save4(body: FavouritePublishDto): FavouriteDto {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/likes/"
        )
        val response = request<FavouriteDto>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as FavouriteDto
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
